package com.reddate.did.sdk.param.req;

import java.io.Serializable;

/**
 * Authority issuer list description data structure
 */
public class AuthorityIssuer implements Serializable {

	/**
	 * Generated by registered did
	 */
	private String did;

	/**
	 * Name of issuing party
	 */
	private String name;

	public String getDid() {
		return did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
